const API_CONFIG = {
   // ANTHROPIC_KEY: 'YOUR-KEY-HERE',
    ADZUNA_APP_ID: 'YOUR_APP_ID',
    ADZUNA_API_KEY: 'YOUR_API_KEY_HERE',
    RAPIDAPI_KEY: 'YOUR_KEY_HERE',

// Optional settings
    AUTO_APPLY_THRESHOLD: 85,
    MAX_AUTO_APPLY_PER_DAY: 20,
    APPLICATION_DELAY_MS: 2000
};
